sudo: required

language: python
python:
  - "2.7"

services:
  - redis
  - mongodb

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libxml2-dev
      - libxslt-dev
      - zlib1g-dev

before_install:
  - sudo mkdir /var/log/yeti
  - sudo chown $USER /var/log/yeti

install:
  - pip install -r requirements.txt
  - git clone https://github.com/yeti-platform/pyeti.git
  - pip install -r pyeti/requirements.txt

script:
  - ./yeti.py webserver &
  - sleep 5
  - curl -I -L http://127.0.0.1:5000
  - cd pyeti
  - nosetests
